### ISSUE TITLE
printing partially when showing leaked

### ISSUE THREAD

**Issue by williamtu** [vmware/chap#11]
Hi,
I have a huge coredump file.
When loaded into chap, command "show leaked" will take more than 5 minute.
I wonder if there is a command for "show leaked" page by page, and by pressing space to continue showing the next page of leaked memory
Thank you!

**Comment by timboddy** [comment]
Hi William,

There is no way at present to show the output of any chap command, including "show leaked", page by page.   I have no immediate plans to support that functionality but it doesn't seem unreasonable for someone to do so at some point.

For now here are some possible alternatives:

If the issue is that the output is large, the standard way to deal with this is to do "redirect on" before "show leaked" and look at the resulting file after the command has finished.

If the issue is that you want to see each leak as it is found, and are concerned that perhaps the output is being delayed by some sort of buffering, it is possible that we could allow some sort of switch to override the buffering behavior.

If the issue is that the set of leaked objects is actually quite large, and you don't really want to see them all, even in a file, perhaps some sort of switch that would allow you to see something like the 1st, the 10th, the 100th, the 1000th member of the set would help.  This would be pretty easy to do, and would have some value for any case where one expects a set of allocations to be quite large and only wants to sample a few members.

**Comment by williamtu** [comment]
thanks a lot~
